import { Event } from "@/types";

export const events: Event[] = [
  {
    id: "evt_001",
    projectId: "proj_001",
    eventName: "user.signup",
    userId: "user_001",
    payload: {
      email: "alex@example.com",
      name: "Alex Johnson",
      source: "landing_page",
    },
    status: "delivered",
    channel: "email",
    receivedAt: "2026-08-22T10:15:00.000Z",
  },
  {
    id: "evt_002",
    projectId: "proj_001",
    eventName: "payment.success",
    userId: "user_002",
    payload: {
      amount: 4999,
      currency: "USD",
      orderId: "order_1024",
    },
    status: "delivered",
    channel: "webhook",
    receivedAt: "2026-08-22T10:22:00.000Z",
  },
  {
    id: "evt_003",
    projectId: "proj_002",
    eventName: "invoice.created",
    userId: "user_003",
    payload: {
      invoiceId: "inv_2048",
      amount: 12900,
      dueDate: "2026-09-01",
    },
    status: "pending",
    channel: "email",
    receivedAt: "2026-08-22T10:30:00.000Z",
  },
  {
    id: "evt_004",
    projectId: "proj_002",
    eventName: "deployment.failed",
    userId: "user_004",
    payload: {
      environment: "production",
      service: "api",
      commit: "a82f91c",
      reason: "Health check failed",
    },
    status: "failed",
    channel: "slack",
    receivedAt: "2026-08-22T10:41:00.000Z",
  },
  {
    id: "evt_005",
    projectId: "proj_003",
    eventName: "password.reset",
    userId: "user_005",
    payload: {
      email: "sam@example.com",
      resetUrl: "https://example.com/reset/token",
      expiresIn: 3600,
    },
    status: "delivered",
    channel: "email",
    receivedAt: "2026-08-22T11:05:00.000Z",
  },
  {
    id: "evt_006",
    projectId: "proj_003",
    eventName: "comment.created",
    userId: "user_006",
    payload: {
      postId: "post_778",
      commentId: "comment_991",
      author: "Taylor Smith",
      preview: "Great work on this!",
    },
    status: "delivered",
    channel: "inapp",
    receivedAt: "2026-08-22T11:18:00.000Z",
  },
  {
    id: "evt_007",
    projectId: "proj_001",
    eventName: "subscription.cancelled",
    userId: "user_007",
    payload: {
      subscriptionId: "sub_4455",
      plan: "pro",
      reason: "Too expensive",
    },
    status: "rate_limited",
    channel: "webhook",
    receivedAt: "2026-08-22T11:32:00.000Z",
  },
  {
    id: "evt_008",
    projectId: "proj_004",
    eventName: "team.member.invited",
    userId: "user_008",
    payload: {
      teamId: "team_123",
      invitedEmail: "jordan@example.com",
      role: "developer",
    },
    status: "pending",
    channel: "email",
    receivedAt: "2026-08-22T11:47:00.000Z",
  },
  {
    id: "evt_009",
    projectId: "proj_004",
    eventName: "build.completed",
    userId: "user_009",
    payload: {
      buildId: "build_8832",
      branch: "main",
      duration: 142,
      testsPassed: 128,
    },
    status: "delivered",
    channel: "slack",
    receivedAt: "2026-08-22T12:03:00.000Z",
  },
  {
    id: "evt_010",
    projectId: "proj_002",
    eventName: "user.login",
    userId: "user_010",
    payload: {
      ip: "192.168.1.42",
      device: "Chrome on macOS",
      location: "Delhi, India",
    },
    status: "delivered",
    channel: "inapp",
    receivedAt: "2026-08-22T12:20:00.000Z",
  },
];
